### ISSUE TITLE
Update version in docs

### ISSUE THREAD

**Issue by purrgrammer** [47deg/fetch#152]
Currently shows `0.6.3` while the last release is `0.7.3`

**Comment by fedefernandez** [comment]
I've manually updated the documentation with the command:
`docs/publishMicrosite`

It needs to set a personal token with repo permissions in the `ORG_GITHUB_TOKEN` env variable as shown in the sbt-microsites docs:
* https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html#publish-using-github4s

Alternatively, you could set the `micrositePushSiteWith` setting to `GHPagesPlugin` and it will use your local credentials, as shown in:
* https://47deg.github.io/sbt-microsites/docs/settings.html
