### ISSUE TITLE
Invalidating the cache

### ISSUE THREAD

**Issue by ChetanBhasin** [47deg/fetch#175]
Perhaps it's possible and I cannot find it, but the default caching solution does not have a way to invalidate a cache item.

This would be super useful for designs when something has changed, through a pub-sub mechanism the application can discard an entry in the cache.

**Comment by purrgrammer** [comment]
>Perhaps it's possible and I cannot find it, but the default caching solution does not have a way to invalidate a cache item.

Exactly, the default implementation is an in-memory cache that has no way to invalidate its items. Take into account that Fetch wants to guarantee that if you ask for the same value more than once inside a Fetch execution it is only fetched once. 

However, nothing is stopping you to implement a custom cache that has a finite time to live. See [the examples folder](https://github.com/47deg/fetch/blob/master/examples/src/test/scala/JedisExample.scala#L154-L185) for an example of a custom cache implementation.
