### ISSUE TITLE
Support for lifting `F[_]: Concurrent` without related Data/DataSource into Fetch

### ISSUE THREAD

**Issue by LiuVII** [47deg/fetch#188]
This is a request for somewhat generalization of the issue brought up in https://github.com/47deg/fetch/issues/181
that was mentioned in the Gitter channel

as Fetch by itself requires `Concurrent` it'd be helpful to have a method like
```scala
def liftF[F[_]: Concurrent](ft: F[T]): Fetch[F, T]
```
to not be restricted for optimized flow for only `IO` monad

**Comment by LiuVII** [comment]
Wooo! Seems like it's close to getting merged, nice!
Is there a release upcoming soon or can there be a snapshot one?

**Comment by purrgrammer** [comment]
After master is built this should be available on 1.0.1-SNAPSHOT

**Comment by purrgrammer** [comment]
It is available on the latest 1.0.1-SNAPSHOT @LiuVII, let me know if you find any problems!
