### ISSUE TITLE
Update Cats 2.0.0 and Monix 3.0.0

### ISSUE THREAD

**Issue by paulpdaniels** [47deg/fetch#211]
Both Cats and Monix recently had major version bumps, cats-effect is at 2.0.0 and monix is at 3.0.0 (though I believe the latter is only for the example docs). We are looking to upgrade our code base but would also need fetch to update as well. 

I can submit a PR to that effect.

**Comment by purrgrammer** [comment]
Happy to merge and do a release with the new versions, thanks @paulpdaniels :heart:
