### ISSUE TITLE
Give users the ability to configure maximum batch sizes

### ISSUE THREAD

**Issue by dialelo** [47deg/fetch#41]

**Comment by ksilin** [comment]
and offsets

**Comment by dialelo** [comment]
Care to elaborate @ksilin?

**Comment by ksilin** [comment]
sure, in order to do sth like this: `def fetchMany(offset: Long, limit: Long): Query[List[Result]]`
Am I misunderstanding the purpose of your issue here?

**Comment by peterneyens** [comment]
Added in #76.
