### ISSUE TITLE
Acknowledgments 

### ISSUE THREAD

**Issue by fwbrasil** [47deg/fetch#42]
I'm not sure I'm correct, but this lib seems to be inspired by similar projects like Clump and Stitch. Could you please add an "Acknowledgments" section to the documentation mentioning it?

BTW, the generic approach for any monad and the typeclasses for sources are very nice! 👏 

Thanks! :)

**Comment by dialelo** [comment]
I mentioned Clump, Stich, Haxl and few others in my talk and thought about adding acknowledgements/alternatives to the documentation but forgot to do it, thanks a lot for mentioning it! I owe a lot to all those projects, standing on the shoulders of giants here :smile: 

Thanks for the kind words!
