### ISSUE TITLE
Update to latest cats and monix

### ISSUE THREAD

**Issue by ngbinh** [47deg/fetch#68]
Now that we have cats `0.7.2` and monix final `2.0.0` released. Please consider upgrade the dependencies and publish a stable version. I tried it myself but got stuck on all the `tailRecM` stuff on the new cats Monad.

**Comment by dialelo** [comment]
Sorry about not releasing, have been very busy and haven't had time to devote to open source. Will look into updating dependencies and releasing as soon as i have time.

**Comment by ngbinh** [comment]
No worries. It's great to have opensource libraries like fetch. I would
love to help if I can.

**Comment by dialelo** [comment]
It'll require some work since the latest cats changes make it more difficult to move computations around using `Eval`.

**Comment by dialelo** [comment]
Thanks for the kind words!

**Comment by RomanIakovlev** [comment]
Hey, it would be super-awesome to get the Fetch with Monix 2.x. It's a total deal-breaker at the moment. It seems to be in the work, but if any help is needed, please do let know.

**Comment by dialelo** [comment]
It has already been merged, will release a new version early next week.

**Comment by juanpedromoreno** [comment]
Fetch 0.4.0 is out!

https://github.com/47deg/fetch/releases/tag/v0.4.0

Thanks @peterneyens !
