### ISSUE TITLE
Create PDF documentation

### ISSUE THREAD

**Issue by frgomes** [47deg/fetch#97]
PDF documentation would be useful when there's no internet connection.

I've created some scripts which work well enough for ``cats``, ``dogs`` and ``fetch``, as shown below:
https://github.com/frgomes/debian-bin/blob/master/bash_30pdf.sh
https://github.com/frgomes/debian-bin/blob/master/bash_30httrack.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_cats.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_dogs.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_fetch.sh

I'm not suggesting you guys adopt these scripts.
However, anyone willing to do that may eventually find some pointers here.

**Comment by dialelo** [comment]
Thanks for sharing these scripts!
