### ISSUE TITLE
Update to cats 0.9.0

### ISSUE THREAD

**Issue by ngbinh** [47deg/fetch#98]
would be nice because it is currently blocking us.

**Comment by peterneyens** [comment]
I already did some preliminary work, but we need a monix 2.2.0 release, which should support Cats 0.9.0.

Then we need to update [sbt-catalysts-extras](https://github.com/47deg/sbt-catalysts-extras) to the latest Cats, Monix and ScalaJS versions.

**Comment by ngbinh** [comment]
thanks for the update!

**Comment by guersam** [comment]
https://github.com/monix/monix/releases/tag/v2.2.0 :tada:

**Comment by raulraja** [comment]
https://github.com/47deg/sbt-catalysts-extras/pull/6

**Comment by dialelo** [comment]
@peterneyens I think we're good to go!

**Comment by raulraja** [comment]
sbt-catalyst-extras is updated but not sure the artifacts have propagated or built for central. @juanpedromoreno is that automated on master merges or do we have to manually release it?

**Comment by juanpedromoreno** [comment]
sbt-catalyst-extras `0.1.3` is now in maven-central.

CC @peterneyens
